{% set name = "pep517" %}
{% set version = "0.9.1" %}
{% set sha256 = "aeb78601f2d1aa461960b43add204cc7955667687fbcf9cdb5170f00556f117f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - flit-core >=2,<3
  run:
    - python
    - importlib-metadata  # [py<38]
    - toml
    - zipp  # [py<38]

test:
  imports:
    - pep517
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pep517
  license: MIT
  license_file: LICENSE
  summary: Wrappers to build Python packages using PEP 517 hooks
